FROM rockylinux/rockylinux:latest

LABEL maintainer="Ryuden <master+passmark@ryuden.org>"

# install
RUN yum update -y \
    && yum install -y \
    gcc \
    git \
    perl \
    make \
    ncurses-compat-libs \
    dmidecode \
    unzip \
    sudo

RUN curl -O https://www.passmark.com/downloads/PerformanceTest_Linux_x86-64.zip \
    && unzip PerformanceTest_Linux_x86-64.zip \
    && rm -f PerformanceTest_Linux_x86-64.zip \
    && chmod +x ./PerformanceTest/pt_linux_x64 

WORKDIR /PerformanceTest/

ENTRYPOINT /PerformanceTest/pt_linux_x64 -r 3 && cat results_all.yml | grep -E --color=always 'SUMM_CPU|SUMM_ME|$'
